server:
  port: 32281

spring:
  datasource:
    url: jdbc:mysql://47.113.198.8:3307/study_circle?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: UxM2sDCAbHM5Eva9Wm2GDGIEb642k/GDWxLnL1mZxqKS4ImoXBBb20WoYoegeVjFV73QFrj/89f4l6pW560K0g==
    type: com.alibaba.druid.pool.DruidDataSource
    # Druid 数据源的配置
    druid:
      connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIhO7Zo24RIkls1KTroymLan7/UzSCkxgHgz58zs4AQ/w+8N97aSL8cQ1ymAOH44tDkX3fm4UfQayYs6Nb7QJN0CAwEAAQ==
      # 连接池初始化时创建的连接数
      initial-size: 20
      # 连接池中保持空闲状态的最小连接数
      min-idle: 20
      # 连接池中同时可用的最大连接数
      max-active: 100
      # 应用程序等待连接的最长时间 ms
      max-wait: 60000
      # 监控视图 Servlet 的配置
      stat-view-servlet:
        enabled: true
        # 监控视图Servlet的URL路径
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      filter:
        # SQL统计信息过滤器的配置
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 3000
        wall:
          enabled: true
        config:
          enabled: true
