

# 自定义微信相关配置信息
wx:
  # 消息模板ID
  templateId:
  mp:
    # 微信公众号的appid
    appId:
    # 信公众号的app secret
    secret:
    # 微信公众号的toke
    token:
    # 微信公众号的EncodingAESKey
    aesKey: wAO
    config-storage:
      redis:
        host: 47.113.198.8
        port: 6379
        password:
      type: jedis
      http-client-type: httpclient
      http-proxy-host:
      http-proxy-password:
      http-proxy-port:
      http-proxy-username:
      key-prefix:

server:
  port:  80
