server:
  port: 32181

spring:
  datasource:
    url: jdbc:mysql://47.113.198.8:3307/study_circle?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: UxM2sDCAbHM5Eva9Wm2GDGIEb642k/GDWxLnL1mZxqKS4ImoXBBb20WoYoegeVjFV73QFrj/89f4l6pW560K0g==
    type: com.alibaba.druid.pool.DruidDataSource
    # Druid 数据源的配置
    druid:
      connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIhO7Zo24RIkls1KTroymLan7/UzSCkxgHgz58zs4AQ/w+8N97aSL8cQ1ymAOH44tDkX3fm4UfQayYs6Nb7QJN0CAwEAAQ==
      # 连接池初始化时创建的连接数
      initial-size: 20
      # 连接池中保持空闲状态的最小连接数
      min-idle: 20
      # 连接池中同时可用的最大连接数
      max-active: 100
      # 应用程序等待连接的最长时间 ms
      max-wait: 60000
      # 监控视图 Servlet 的配置
      stat-view-servlet:
        enabled: true
        # 监控视图Servlet的URL路径
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      filter:
        # SQL统计信息过滤器的配置
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 3000
        wall:
          enabled: true
        config:
          enabled: true


############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
